version: '3.8'

services:
  app:
    container_name: lgbtq-matrimony-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/lgbtq_matrimony_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=yourSuperSecretKey123!
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon src/server.js

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
